/** Masked frontend routes and their upstream endpoints. */
export const API_ROUTES = [
  { masked: '/api/config', method: 'POST', original: '/config' },
  { masked: '/api/fetch', method: 'POST', original: '/shipments' },
  { masked: '/api/fetch-details', method: 'GET', original: '/tracking/exchange/shipment (optional ?order_id=)' },
  { masked: '/api/fetch-pincode', method: 'GET', original: '/get_city_state?pincode={pincode}' },
  { masked: '/api/fetch-skus', method: 'GET', original: 'tracking/sku (params: product_id, sku, variant)' },
  { masked: '/api/verify', method: 'POST', original: 'get_domain' },
  { masked: '/api/validate-token', method: 'GET', original: 'tracking/temp_token/validate (params: token, origin, referer)' },
  { masked: '/api/gen-otp', method: 'POST', original: 'generate-otp' },
  { masked: '/api/ver-otp', method: 'POST', original: 'verify-otp' },
  { masked: '/api/orders', method: 'POST', original: 'verify/shopify-order' },
  { masked: '/api/products', method: 'POST', original: 'products' },
  { masked: '/api/sku-details', method: 'POST', original: 'fetch-sku-exchange-data' },
  { masked: '/api/get-notes', method: 'POST', original: 'get-notes' },
  { masked: '/api/cancel', method: 'POST', original: 'customer-rto (params: ndrtype=rto)' },
  { masked: '/api/reattempt', method: 'POST', original: 'customer-reattempt' },
  { masked: '/api/submit-query', method: 'POST', original: 'contact-us' },
  { masked: '/api/submit-feedback', method: 'POST', original: 'feedback' },
  { masked: '/api/calculate-refund', method: 'POST', original: 'refund_calculation' },
  { masked: '/api/calculate-refund-shopify', method: 'POST', original: 'plugin-refund_calculation' },
  { masked: '/api/create-btp-order', method: 'POST', original: 'create-return-exchange (FormData: body + images)' },
  { masked: '/api/create/return-exchange', method: 'POST', original: 'create/return-exchange (FormData: req_body + images)' },
  { masked: '/api/payment-gateway', method: 'POST', original: 'payment_gateway_order' },
  { masked: '/api/razorpay-payment-status', method: 'POST', original: 'razorpay_payment_status' },
  { masked: '/api/verify-captcha', method: 'POST', original: 'https://www.google.com/recaptcha/api/siteverify (Google reCAPTCHA; not backend)' },
  { masked: '/api/log-api-call', method: 'POST', original: 'Internal only – writes to logs/api-logs.txt; no external API call' },
];
